version: '3.7'

volumes:
    logs:
        driver: local

networks:
  api:
    driver: bridge

services:
    slim:
        build: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - "db"
        networks:
            - "api"
    db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        #restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: oauth2
        networks:
            - "api"
    front:
        image: ebiven/vue-cli
        command: npm run serve
        volumes:
            - ./frontend/:/code
        ports:
            - "9090:8080"
        depends_on:
            - "slim"
        networks:
            - "api"
        links:
            - slim